// This file is generated audit guidance.
// Do not import it into runtime code until avatar support is intentionally implemented.
// Do not assume referenced VRMs exist unless conversion/runtime tests pass.

export const GENERATED_AVATAR_CONFIG_PREVIEW = [
  {
    id: 'woody',
    label: 'Woody',
    type: 'vrm',
    url: '/avatars/woody.vrm',
    profile: 'humanoid',
    warningLevel: 'experimental',
    enabledControls: ["arms", "feet", "hands", "head", "legs", "root_motion", "toes", "upper_body"],
    disabledControls: ["face_touch", "facial_expressions", "fingers"],
    adapterSpec: 'model-audits/woody/avatar-adapter-spec.json',
  },
  {
    id: 'darth-vader',
    label: 'Darth Vader',
    type: 'vrm',
    url: '/avatars/darth-vader.vrm',
    profile: 'humanoid',
    warningLevel: 'conversion-needed',
    enabledControls: ["arms", "feet", "fingers", "hands", "head", "legs", "root_motion", "toes", "upper_body"],
    disabledControls: ["face_touch", "facial_expressions"],
    adapterSpec: 'model-audits/darth-vader/avatar-adapter-spec.json',
  },
  {
    id: 'fortnite-batman',
    label: 'Fortnite Batman',
    type: 'vrm',
    url: '/avatars/fortnite-batman.vrm',
    profile: 'humanoid',
    warningLevel: 'conversion-needed',
    enabledControls: ["arms", "feet", "fingers", "hands", "head", "legs", "root_motion", "toes", "upper_body"],
    disabledControls: ["face_touch", "facial_expressions"],
    adapterSpec: 'model-audits/fortnite-batman/avatar-adapter-spec.json',
  },
  {
    id: 'iron-man',
    label: 'Iron Man',
    type: 'vrm',
    url: '/avatars/iron-man.vrm',
    profile: 'humanoid',
    warningLevel: 'conversion-needed',
    enabledControls: ["arms", "feet", "fingers", "hands", "head", "legs", "root_motion", "toes", "upper_body"],
    disabledControls: ["face_touch", "facial_expressions"],
    adapterSpec: 'model-audits/iron-man/avatar-adapter-spec.json',
  },
  {
    id: 'shrek',
    label: 'Shrek',
    type: 'vrm',
    url: '/avatars/shrek.vrm',
    profile: 'humanoid',
    warningLevel: 'conversion-needed',
    enabledControls: ["arms", "feet", "hands", "head", "legs", "root_motion", "upper_body"],
    disabledControls: ["face_touch", "facial_expressions", "fingers", "toes"],
    adapterSpec: 'model-audits/shrek/avatar-adapter-spec.json',
  },
  {
    id: 'spider-man-no-way-home',
    label: 'Spider-Man No Way Home',
    type: 'vrm',
    url: '/avatars/spider-man-no-way-home.vrm',
    profile: 'humanoid',
    warningLevel: 'conversion-needed',
    enabledControls: ["arms", "feet", "hands", "head", "legs", "root_motion", "toes", "upper_body"],
    disabledControls: ["face_touch", "facial_expressions", "fingers"],
    adapterSpec: 'model-audits/spider-man-no-way-home/avatar-adapter-spec.json',
  },
  {
    id: 'spider-man-playstation',
    label: 'Spider-Man PlayStation',
    type: 'vrm',
    url: '/avatars/spider-man-playstation.vrm',
    profile: 'humanoid',
    warningLevel: 'conversion-needed',
    enabledControls: ["arms", "feet", "hands", "head", "legs", "root_motion", "toes", "upper_body"],
    disabledControls: ["face_touch", "facial_expressions", "fingers"],
    adapterSpec: 'model-audits/spider-man-playstation/avatar-adapter-spec.json',
  },
  {
    id: 'amazing-spider-man-2',
    label: 'The Amazing Spider-Man 2',
    type: 'vrm',
    url: '/avatars/amazing-spider-man-2.vrm',
    profile: 'humanoid',
    warningLevel: 'conversion-needed',
    enabledControls: ["arms", "feet", "hands", "head", "legs", "root_motion", "toes", "upper_body"],
    disabledControls: ["face_touch", "facial_expressions", "fingers"],
    adapterSpec: 'model-audits/amazing-spider-man-2/avatar-adapter-spec.json',
  },
  {
    id: 'terminator-t-800',
    label: 'Terminator T-800',
    type: 'vrm',
    url: '/avatars/terminator-t-800.vrm',
    profile: 'humanoid',
    warningLevel: 'conversion-needed',
    enabledControls: ["arms", "feet", "hands", "head", "legs", "root_motion", "toes", "upper_body"],
    disabledControls: ["face_touch", "facial_expressions", "fingers"],
    adapterSpec: 'model-audits/terminator-t-800/avatar-adapter-spec.json',
  },
  {
    id: 'jack-sparrow',
    label: 'Jack Sparrow',
    type: 'vrm',
    url: '/avatars/jack-sparrow.vrm',
    profile: 'humanoid_with_offsets',
    warningLevel: 'conversion-needed',
    enabledControls: ["arms", "feet", "hands", "head", "legs", "toes", "upper_body"],
    disabledControls: ["face_touch", "facial_expressions", "fingers"],
    adapterSpec: 'model-audits/jack-sparrow/avatar-adapter-spec.json',
  },
  {
    id: 'elsa',
    label: 'Elsa',
    type: 'vrm',
    url: '/avatars/elsa.vrm',
    profile: 'humanoid_with_offsets',
    warningLevel: 'cleanup-needed',
    enabledControls: ["arms", "hands", "head", "upper_body"],
    disabledControls: ["face_touch", "facial_expressions", "feet", "fingers", "toes"],
    adapterSpec: 'model-audits/elsa/avatar-adapter-spec.json',
  },
  {
    id: 'grogu',
    label: 'Grogu',
    type: 'vrm',
    url: '/avatars/grogu.vrm',
    profile: 'creature',
    warningLevel: 'creature-profile-needed',
    enabledControls: ["arms", "creature_head", "creature_jaw", "legs"],
    disabledControls: ["face_touch", "facial_expressions", "fingers", "standard_humanoid_full_body"],
    adapterSpec: 'model-audits/grogu/avatar-adapter-spec.json',
  },
  {
    id: 'king-kong',
    label: 'King Kong',
    type: 'vrm',
    url: '/avatars/king-kong.vrm',
    profile: 'creature',
    warningLevel: 'creature-profile-needed',
    enabledControls: ["arms", "creature_head", "creature_jaw", "legs"],
    disabledControls: ["face_touch", "facial_expressions", "fingers", "standard_humanoid_full_body"],
    adapterSpec: 'model-audits/king-kong/avatar-adapter-spec.json',
  },
  {
    id: 'olaf',
    label: 'Olaf',
    type: 'vrm',
    url: '/avatars/olaf.vrm',
    profile: 'creature',
    warningLevel: 'creature-profile-needed',
    enabledControls: ["arms", "creature_head", "legs"],
    disabledControls: ["face_touch", "facial_expressions", "fingers", "standard_humanoid_full_body"],
    adapterSpec: 'model-audits/olaf/avatar-adapter-spec.json',
  },
  {
    id: 'godzilla',
    label: 'Godzilla',
    type: 'vrm',
    url: '/avatars/godzilla.vrm',
    profile: 'creature',
    warningLevel: 'creature-profile-needed',
    enabledControls: ["arms", "creature_head", "creature_jaw", "legs"],
    disabledControls: ["face_touch", "facial_expressions", "fingers", "standard_humanoid_full_body"],
    adapterSpec: 'model-audits/godzilla/avatar-adapter-spec.json',
  },
  {
    id: 'xenomorph',
    label: 'Xenomorph',
    type: 'vrm',
    url: '/avatars/xenomorph.vrm',
    profile: 'creature',
    warningLevel: 'creature-profile-needed',
    enabledControls: ["creature_head", "creature_jaw", "legs"],
    disabledControls: ["face_touch", "facial_expressions", "fingers", "standard_humanoid_full_body"],
    adapterSpec: 'model-audits/xenomorph/avatar-adapter-spec.json',
  },
  {
    id: 'rigged-hand',
    label: 'Rigged Hand',
    type: 'vrm',
    url: '/avatars/rigged-hand.vrm',
    profile: 'hand_only',
    warningLevel: 'hand-only',
    enabledControls: ["fingers", "hands"],
    disabledControls: ["arms", "face_touch", "facial_expressions", "feet", "head", "legs", "root_motion", "toes", "torso", "upper_body"],
    adapterSpec: 'model-audits/rigged-hand/avatar-adapter-spec.json',
  },
  {
    id: 'teal-v2',
    label: 'Teal v2',
    type: 'vrm',
    url: '/avatars/teal-v2.vrm',
    profile: 'humanoid_with_offsets',
    warningLevel: 'cleanup-needed',
    enabledControls: ["arms", "feet", "hands", "head", "legs", "upper_body"],
    disabledControls: ["face_touch", "facial_expressions", "fingers", "toes"],
    adapterSpec: 'model-audits/teal-v2/avatar-adapter-spec.json',
  },
  {
    id: 'buzz-lightyear',
    label: 'Buzz Lightyear',
    type: 'vrm',
    url: '/avatars/buzz-lightyear.vrm',
    profile: 'humanoid_with_offsets',
    warningLevel: 'cleanup-needed',
    enabledControls: ["arms", "hands", "head", "upper_body"],
    disabledControls: ["face_touch", "facial_expressions", "feet", "fingers", "toes"],
    adapterSpec: 'model-audits/buzz-lightyear/avatar-adapter-spec.json',
  },
  {
    id: 'baby-yoda',
    label: 'Baby Yoda',
    type: 'vrm',
    url: '/avatars/baby-yoda.vrm',
    profile: 'creature',
    warningLevel: 'creature-profile-needed',
    enabledControls: ["creature_head"],
    disabledControls: ["face_touch", "facial_expressions", "fingers", "standard_humanoid_full_body"],
    adapterSpec: 'model-audits/baby-yoda/avatar-adapter-spec.json',
  },
] as const;
