# build-cave-modules.py — Checkpoint 09 cave/arch module realization.
#
# Runs headless inside Blender (invoked by bake-caves.mjs):
#   Blender --background --factory-startup --python build-cave-modules.py -- \
#       <resolved-plan.json> <out-dir>
#
# Blender's role is deliberately narrow (kit GLB import + BVH raycasts for
# the AO bake). All geometry is generated by explicit deterministic code from
# the hand-authored plan (cave-plan.mjs → resolved JSON): double-walled pipe
# lofts (inner navigable surface + rock exterior welded by mouth annuli),
# the arch arc, and fixed kit-piece placements. No randomness, no wall
# clock, no Blender modifiers — two runs must produce byte-identical output
# (bake-caves.mjs --verify proves it).
#
# Output per module: <id>.rawmesh —
#   magic 'BARAWM02' | u32 vertCount | u32 triCount | u32 shellVertCount | u32 shellTriCount |
#   f32 pos[3v] | f32 nrm[3v] | f32 ao[v] | u32 idx[3t]
# in GAME space (y-up, meters, world coordinates).
# Prefix (shellVertCount / shellTriCount) is the authored navigable shell;
# the remainder is Kenney dressing (render only — not collision/BVH).

import bpy
import json
import math
import os
import struct
import sys

from mathutils.bvhtree import BVHTree

argv = sys.argv[sys.argv.index("--") + 1:]
PLAN_PATH, OUT_DIR = argv[0], argv[1]

with open(PLAN_PATH, "r") as f:
    PLAN = json.load(f)

SHELL = PLAN["shell"]
KIT_DIR = PLAN["kitDir"]

# ---------------------------------------------------------------------------
# Deterministic value noise (same integer-hash family as the region bake)
# ---------------------------------------------------------------------------

def _imul(a, b):
    return ((a & 0xFFFFFFFF) * (b & 0xFFFFFFFF)) & 0xFFFFFFFF

def hash2(ix, iz, seed):
    h = (ix * 374761393 + iz * 668265263 + seed * 2246822519) & 0xFFFFFFFF
    h = _imul(h ^ (h >> 13), 1274126177)
    h ^= h >> 16
    return h / 4294967296.0

def vnoise(x, z, seed):
    ix, iz = math.floor(x), math.floor(z)
    fx, fz = x - ix, z - iz
    ux = fx * fx * (3 - 2 * fx)
    uz = fz * fz * (3 - 2 * fz)
    a = hash2(ix, iz, seed)
    b = hash2(ix + 1, iz, seed)
    c = hash2(ix, iz + 1, seed)
    d = hash2(ix + 1, iz + 1, seed)
    return (a * (1 - ux) + b * ux) * (1 - uz) + (c * (1 - ux) + d * ux) * uz

# ---------------------------------------------------------------------------
# Plan interpolation (mirrors cave-plan.mjs stationAt/centerAt semantics)
# ---------------------------------------------------------------------------

def clamp(v, a, b):
    return a if v < a else b if v > b else v

def lerp(a, b, t):
    return a + (b - a) * t

def station_at(mod, s):
    st = mod["stations"]
    sc = clamp(s, st[0]["s"], st[-1]["s"])
    i = 0
    while i < len(st) - 2 and st[i + 1]["s"] < sc:
        i += 1
    a, b = st[i], st[i + 1]
    t = 0.0 if b["s"] == a["s"] else (sc - a["s"]) / (b["s"] - a["s"])
    return {
        "lat": lerp(a["lat"], b["lat"], t),
        "floorY": lerp(a["floorY"], b["floorY"], t),
        "halfW": lerp(a["halfW"], b["halfW"], t),
        "height": lerp(a["height"], b["height"], t),
        "hood": a["hood"] if t < 0.5 else b["hood"],
    }

def center_at(mod, s):
    f = mod["frame"]
    v = station_at(mod, s)
    x = f["ax"] + f["ux"] * s + f["px"] * v["lat"]
    z = f["az"] + f["uz"] * s + f["pz"] * v["lat"]
    e = 0.5
    v2 = station_at(mod, s + e)
    v1 = station_at(mod, s - e)
    d_lat = (v2["lat"] - v1["lat"]) / (2 * e)
    hx = f["ux"] + f["px"] * d_lat
    hz = f["uz"] + f["pz"] * d_lat
    hl = math.hypot(hx, hz) or 1.0
    return {"x": x, "z": z, "hx": hx / hl, "hz": hz / hl, **v}

# ---------------------------------------------------------------------------
# Mesh accumulator
# ---------------------------------------------------------------------------

class MeshAcc:
    def __init__(self):
        self.pos = []   # flat floats x,y,z
        self.idx = []   # flat ints

    def add_vert(self, x, y, z):
        self.pos.extend((x, y, z))
        return len(self.pos) // 3 - 1

    def add_tri(self, a, b, c):
        self.idx.extend((a, b, c))

    def vert_count(self):
        return len(self.pos) // 3

# ---------------------------------------------------------------------------
# Pipe loft (double-walled cave solid)
# ---------------------------------------------------------------------------

RADIAL = int(SHELL["RADIAL"])

def ring_point(c, k, inner, hood, seed_amp):
    """Ring vertex k (0..RADIAL-1) of the section at centerline sample c."""
    ang = 2 * math.pi * k / RADIAL
    ca, sa = math.cos(ang), math.sin(ang)
    # lateral direction (plan-lat): F×up in XZ
    lx, lz = -c["hz"], c["hx"]
    if inner:
        half_w = c["halfW"]
        up_h = c["height"] * SHELL["DOME_UP_FRAC"]
        dn_h = c["height"] * (1 - SHELL["DOME_UP_FRAC"])
        cy = c["floorY"] + dn_h
        amp = SHELL["NOISE_AMP_IN"]
        wavelen = SHELL["NOISE_WAVELEN_IN"]
    else:
        half_w = c["halfW"] + SHELL["THICKNESS"] + c.get("collar", 0.0)
        up_h = c["height"] * SHELL["DOME_UP_FRAC"] + SHELL["THICKNESS"]
        dn_h = c["height"] * (1 - SHELL["DOME_UP_FRAC"]) + SHELL["THICKNESS"]
        cy = c["floorY"] + c["height"] * (1 - SHELL["DOME_UP_FRAC"])
        amp = SHELL["NOISE_AMP_OUT"] * (1.35 if hood else 1.0)
        wavelen = SHELL["NOISE_WAVELEN_OUT"]
    # radial rock displacement (never on the flat floor chord)
    n = vnoise(c["s"] / wavelen * 4.0 + k * 0.61, k * 0.37 + (0.0 if inner else 51.7),
               seed_amp) * 2 - 1
    r_disp = n * amp * (0.0 if sa < SHELL["FLOOR_FLAT_SIN"] else 1.0)
    w = half_w + r_disp
    h_up = up_h + r_disp * 0.6
    h_dn = dn_h
    x = c["x"] + lx * ca * w
    z = c["z"] + lz * ca * w
    y = cy + (sa * h_up if sa >= 0 else sa * h_dn)
    if inner:
        floor_line = c["floorY"]
    else:
        floor_line = c["floorY"] - SHELL["THICKNESS"]
    if sa < SHELL["FLOOR_FLAT_SIN"]:
        y = floor_line
    return (x, y, z)

def build_pipe(acc, mod):
    """Double-walled pipe: inner + outer lofts stitched by mouth annuli and
    (optionally) an end-cap dome pair. Returns nothing (fills acc)."""
    s0 = mod["stations"][0]["s"] - SHELL["LIP_OVERHANG"]
    s1 = mod["stations"][-1]["s"] + (0.0 if mod.get("endCap") else SHELL["LIP_OVERHANG"])
    steps = max(2, int(math.ceil((s1 - s0) / SHELL["STEP"])))
    samples = []
    for i in range(steps + 1):
        s = s0 + (s1 - s0) * i / steps
        c = center_at(mod, s)
        c["s"] = s
        # collar flare within 3 m of each open mouth ring
        d_mouth = min(abs(s - mod["stations"][0]["s"]),
                      1e9 if mod.get("endCap") else abs(s - mod["stations"][-1]["s"]))
        c["collar"] = SHELL["COLLAR_FLARE"] * max(0.0, 1.0 - d_mouth / 3.0)
        samples.append(c)

    inner_rings = []
    outer_rings = []
    for c in samples:
        inner_rings.append([acc.add_vert(*ring_point(c, k, True, c["hood"], PLAN["seeds"]["shellNoise"]))
                            for k in range(RADIAL)])
        outer_rings.append([acc.add_vert(*ring_point(c, k, False, c["hood"], PLAN["seeds"]["outerNoise"]))
                            for k in range(RADIAL)])

    def stitch(rings, flip):
        for i in range(len(rings) - 1):
            ra, rb = rings[i], rings[i + 1]
            for k in range(RADIAL):
                k2 = (k + 1) % RADIAL
                a, b, cc, d = ra[k], ra[k2], rb[k], rb[k2]
                if flip:
                    acc.add_tri(a, cc, b)
                    acc.add_tri(b, cc, d)
                else:
                    acc.add_tri(a, b, cc)
                    acc.add_tri(b, d, cc)

    # inner surface faces INTO the tunnel; outer faces away from the rock
    stitch(inner_rings, flip=True)
    stitch(outer_rings, flip=False)

    def annulus(ri, ro, at_start):
        for k in range(RADIAL):
            k2 = (k + 1) % RADIAL
            a, b = ri[k], ri[k2]
            cc, d = ro[k], ro[k2]
            if at_start:
                acc.add_tri(a, b, cc)
                acc.add_tri(b, d, cc)
            else:
                acc.add_tri(a, cc, b)
                acc.add_tri(b, cc, d)

    annulus(inner_rings[0], outer_rings[0], True)
    if mod.get("endCap"):
        # dome caps: shrink three synthetic rings then a center fan
        base = samples[-1]
        prev_i = inner_rings[-1]
        prev_o = outer_rings[-1]
        for j, f in enumerate((0.66, 0.35)):
            c = dict(base)
            c["s"] = base["s"] + (j + 1) * 1.2
            c["halfW"] = base["halfW"] * f
            c["height"] = base["height"] * f
            c["floorY"] = base["floorY"] + base["height"] * (1 - f) * 0.35
            c["collar"] = 0.0
            ri = [acc.add_vert(*ring_point(c, k, True, False, PLAN["seeds"]["shellNoise"]))
                  for k in range(RADIAL)]
            ro = [acc.add_vert(*ring_point(c, k, False, False, PLAN["seeds"]["outerNoise"]))
                  for k in range(RADIAL)]
            for k in range(RADIAL):
                k2 = (k + 1) % RADIAL
                acc.add_tri(prev_i[k], ri[k], prev_i[k2])
                acc.add_tri(prev_i[k2], ri[k], ri[k2])
                acc.add_tri(prev_o[k], prev_o[k2], ro[k])
                acc.add_tri(prev_o[k2], ro[k2], ro[k])
            prev_i, prev_o = ri, ro
        tip = center_at(mod, base["s"])
        ci = acc.add_vert(tip["x"] + tip["hx"] * 3.4,
                          base["floorY"] + base["height"] * 0.45,
                          tip["z"] + tip["hz"] * 3.4)
        co = acc.add_vert(tip["x"] + tip["hx"] * (3.4 + SHELL["THICKNESS"]),
                          base["floorY"] + base["height"] * 0.45,
                          tip["z"] + tip["hz"] * (3.4 + SHELL["THICKNESS"]))
        for k in range(RADIAL):
            k2 = (k + 1) % RADIAL
            acc.add_tri(prev_i[k], ci, prev_i[k2])
            acc.add_tri(prev_o[k], prev_o[k2], co)
    else:
        annulus(inner_rings[-1], outer_rings[-1], False)

    # mouth skirts: lower-half outer ring extruded down/out at each open end
    def skirt(ring_idx, c):
        ring = outer_rings[ring_idx]
        lx, lz = -c["hz"], c["hx"]
        pts = []
        for k in range(RADIAL):
            ang = 2 * math.pi * k / RADIAL
            if math.sin(ang) < 0.15:
                px, py, pz = acc.pos[ring[k] * 3], acc.pos[ring[k] * 3 + 1], acc.pos[ring[k] * 3 + 2]
                out = 1.5 * math.cos(ang)
                v = acc.add_vert(px + lx * out, py - SHELL["SKIRT_DROP"], pz + lz * out)
                pts.append((k, ring[k], v))
        for i in range(len(pts) - 1):
            k_a, top_a, bot_a = pts[i]
            k_b, top_b, bot_b = pts[i + 1]
            if k_b == k_a + 1:
                acc.add_tri(top_a, bot_a, top_b)
                acc.add_tri(top_b, bot_a, bot_b)
                acc.add_tri(top_a, top_b, bot_a)  # double-wound (visible either side)
                acc.add_tri(top_b, bot_b, bot_a)

    skirt(0, samples[0])
    if not mod.get("endCap"):
        skirt(len(samples) - 1, samples[-1])

# ---------------------------------------------------------------------------
# Arch loft (solid arc of rounded-rectangular rock)
# ---------------------------------------------------------------------------

def build_arch(acc, arch):
    yaw = arch["yaw"]
    fx, fz = math.sin(yaw), math.cos(yaw)         # swim-through direction
    px, pz = math.cos(yaw), -math.sin(yaw)        # leg line (perpendicular)
    cx, cz = arch["center"]["x"], arch["center"]["z"]
    steps = int(arch["arcSteps"])
    ring_w = arch["ringW"]
    ring_d = arch["ringD"]

    def foot_y(t):
        return lerp(arch["footTopYA"], arch["footTopYB"], t)

    # arc stations: legs extended below the foot tops to the embedded bottoms
    stations = []
    stations.append({"px": -arch["legOffset"], "y": arch["footBottomYA"], "leg": True, "t": 0.0})
    for i in range(steps + 1):
        t = i / steps
        th = math.pi * t
        off = -math.cos(th) * arch["legOffset"]
        y = foot_y(t) + math.sin(th) * (arch["crownY"] - foot_y(t))
        stations.append({"px": off, "y": y, "leg": False, "t": t})
    stations.append({"px": arch["legOffset"], "y": arch["footBottomYB"], "leg": True, "t": 1.0})

    rings = []
    n_r = 16
    for si, st in enumerate(stations):
        # ring tangent: along the arc (approximate by neighbors)
        prev_s = stations[max(0, si - 1)]
        next_s = stations[min(len(stations) - 1, si + 1)]
        tx = next_s["px"] - prev_s["px"]
        ty = next_s["y"] - prev_s["y"]
        tl = math.hypot(tx, ty) or 1.0
        tx, ty = tx / tl, ty / tl
        # ring axes: n = perpendicular of tangent in the arc plane; d = yaw dir
        nx_, ny_ = -ty, tx
        ring = []
        for k in range(n_r):
            ang = 2 * math.pi * k / n_r
            # superellipse (squarish rock section)
            ca, sa = math.cos(ang), math.sin(ang)
            m = (abs(ca) ** 3 + abs(sa) ** 3) ** (1.0 / 3.0) or 1.0
            u = (ca / m) * (ring_w / 2)
            v = (sa / m) * (ring_d / 2)
            nse = vnoise(si * 0.83 + k * 0.51, k * 0.29, PLAN["seeds"]["shellNoise"] + 7) * 2 - 1
            u *= 1.0 + nse * 0.14
            v *= 1.0 + nse * 0.10
            wx = cx + px * (st["px"] + nx_ * u) + fx * v
            wy = st["y"] + ny_ * u
            wz = cz + pz * (st["px"] + nx_ * u) + fz * v
            ring.append(acc.add_vert(wx, wy, wz))
        rings.append(ring)

    for i in range(len(rings) - 1):
        ra, rb = rings[i], rings[i + 1]
        for k in range(n_r):
            k2 = (k + 1) % n_r
            acc.add_tri(ra[k], ra[k2], rb[k])
            acc.add_tri(ra[k2], rb[k2], rb[k])
    # foot caps (buried)
    for ring, top in ((rings[0], True), (rings[-1], False)):
        cxv = sum(acc.pos[i * 3] for i in ring) / n_r
        cyv = sum(acc.pos[i * 3 + 1] for i in ring) / n_r
        czv = sum(acc.pos[i * 3 + 2] for i in ring) / n_r
        c = acc.add_vert(cxv, cyv, czv)
        for k in range(n_r):
            k2 = (k + 1) % n_r
            if top:
                acc.add_tri(ring[k], c, ring[k2])
            else:
                acc.add_tri(ring[k], ring[k2], c)

# ---------------------------------------------------------------------------
# Kenney kit pieces (geometry only; converted glTF→game space)
# ---------------------------------------------------------------------------

_kit_cache = {}

def kit_piece(name):
    """Canonical piece arrays in game space: centered on XZ, base at y 0."""
    if name in _kit_cache:
        return _kit_cache[name]
    path = os.path.join(KIT_DIR, name + ".glb")
    bpy.ops.wm.read_factory_settings(use_empty=True)
    bpy.ops.import_scene.gltf(filepath=path)
    pos = []
    idx = []
    base = 0
    meshes = [o for o in bpy.data.objects if o.type == "MESH"]
    meshes.sort(key=lambda o: o.name)
    for o in meshes:
        o.data.calc_loop_triangles()
        mw = o.matrix_world
        for vtx in o.data.vertices:
            w = mw @ vtx.co
            # Blender (z-up) → game/glTF (y-up): g = (bx, bz, -by)
            pos.append((w.x, w.z, -w.y))
        for tri in o.data.loop_triangles:
            a, b, c = tri.vertices
            # axis conversion mirrors handedness? No: it is a proper rotation
            # (determinant +1), so winding is preserved.
            idx.append((base + a, base + b, base + c))
        base += len(o.data.vertices)
    # canonicalize: center XZ, base at y = 0
    min_y = min(p[1] for p in pos)
    cx = (min(p[0] for p in pos) + max(p[0] for p in pos)) / 2
    cz = (min(p[2] for p in pos) + max(p[2] for p in pos)) / 2
    pos = [(p[0] - cx, p[1] - min_y, p[2] - cz) for p in pos]
    _kit_cache[name] = (pos, idx)
    return _kit_cache[name]

def place_kit(acc, mod, entry):
    pos, idx = kit_piece(entry["piece"])
    if "arcT" in entry:  # arch-frame placement
        arch = mod
        yaw = arch["yaw"]
        px, pz = math.cos(yaw), -math.sin(yaw)
        t = entry["arcT"]
        th = math.pi * t
        off = -math.cos(th) * arch["legOffset"]
        foot = lerp(arch["footTopYA"], arch["footTopYB"], t)
        sign = 1.0 if off >= 0 else -1.0
        out = float(entry.get("outward", 0.0)) * sign
        wx = arch["center"]["x"] + px * (off + out)
        wz = arch["center"]["z"] + pz * (off + out)
        wy = foot + entry["dy"]
        world_yaw = yaw + entry["yawDeg"] * math.pi / 180
    else:
        c = center_at(mod, entry["s"])
        lx, lz = -c["hz"], c["hx"]
        wx = c["x"] + lx * entry["lat"]
        wz = c["z"] + lz * entry["lat"]
        wy = c["floorY"] + entry["dy"]
        heading = math.atan2(c["hx"], c["hz"])
        world_yaw = heading + entry["yawDeg"] * math.pi / 180
    s = entry["scale"]
    cy, sy = math.cos(world_yaw), math.sin(world_yaw)
    base = acc.vert_count()
    for p in pos:
        x = p[0] * s
        y = p[1] * s
        z = p[2] * s
        rx = x * cy + z * sy
        rz = -x * sy + z * cy
        acc.add_vert(wx + rx, wy + y, wz + rz)
    for a, b, c3 in idx:
        acc.add_tri(base + a, base + b, base + c3)

# ---------------------------------------------------------------------------
# Normals (area-weighted, deterministic) + AO (cosine-weighted BVH rays)
# ---------------------------------------------------------------------------

def compute_normals(pos, idx):
    n = [0.0] * len(pos)
    for t in range(0, len(idx), 3):
        a, b, c = idx[t] * 3, idx[t + 1] * 3, idx[t + 2] * 3
        ux, uy, uz = pos[b] - pos[a], pos[b + 1] - pos[a + 1], pos[b + 2] - pos[a + 2]
        vx, vy, vz = pos[c] - pos[a], pos[c + 1] - pos[a + 1], pos[c + 2] - pos[a + 2]
        cx = uy * vz - uz * vy
        cy = uz * vx - ux * vz
        cz = ux * vy - uy * vx
        for vi in (a, b, c):
            n[vi] += cx
            n[vi + 1] += cy
            n[vi + 2] += cz
    for i in range(0, len(n), 3):
        l = math.sqrt(n[i] ** 2 + n[i + 1] ** 2 + n[i + 2] ** 2) or 1.0
        n[i] /= l
        n[i + 1] /= l
        n[i + 2] /= l
    return n

# fixed cosine-distributed hemisphere directions (golden spiral)
AO_RAYS = 48
AO_DIST = 45.0
_dirs = []
for i in range(AO_RAYS):
    u1 = (i + 0.5) / AO_RAYS
    r = math.sqrt(u1)
    phi = i * 2.399963229728653  # golden angle
    _dirs.append((r * math.cos(phi), r * math.sin(phi), math.sqrt(max(0.0, 1 - u1))))

def compute_ao(pos, nrm, idx):
    verts = [(pos[i], pos[i + 1], pos[i + 2]) for i in range(0, len(pos), 3)]
    polys = [(idx[t], idx[t + 1], idx[t + 2]) for t in range(0, len(idx), 3)]
    tree = BVHTree.FromPolygons(verts, polys, all_triangles=True)
    ao = []
    for v in range(len(verts)):
        nx, ny, nz = nrm[v * 3], nrm[v * 3 + 1], nrm[v * 3 + 2]
        # tangent frame around the normal (deterministic branch)
        if abs(ny) < 0.92:
            tx, ty, tz = -nz, 0.0, nx  # n × (0,1,0)
        else:
            tx, ty, tz = 1.0, 0.0, 0.0
        tl = math.sqrt(tx * tx + ty * ty + tz * tz) or 1.0
        tx, ty, tz = tx / tl, ty / tl, tz / tl
        bx = ny * tz - nz * ty
        by = nz * tx - nx * tz
        bz = nx * ty - ny * tx
        ox = verts[v][0] + nx * 0.06
        oy = verts[v][1] + ny * 0.06
        oz = verts[v][2] + nz * 0.06
        open_n = 0
        for dx, dy, dz in _dirs:
            wx = tx * dx + bx * dy + nx * dz
            wy = ty * dx + by * dy + ny * dz
            wz = tz * dx + bz * dy + nz * dz
            hit = tree.ray_cast((ox, oy, oz), (wx, wy, wz), AO_DIST)
            if hit[0] is None:
                open_n += 1
        ao.append(open_n / AO_RAYS)
    return ao

# ---------------------------------------------------------------------------
# Build every module and write raw meshes
# ---------------------------------------------------------------------------

os.makedirs(OUT_DIR, exist_ok=True)
report = []
for mod in PLAN["modules"]:
    acc = MeshAcc()
    if mod["kind"] == "pipe":
        build_pipe(acc, mod)
    else:
        build_arch(acc, mod)
    shell_v = acc.vert_count()
    shell_t = len(acc.idx) // 3
    for entry in mod.get("kit", []):
        place_kit(acc, mod, entry)
    nrm = compute_normals(acc.pos, acc.idx)
    ao = compute_ao(acc.pos, nrm, acc.idx)
    out = os.path.join(OUT_DIR, mod["id"] + ".rawmesh")
    with open(out, "wb") as f:
        f.write(b"BARAWM02")
        f.write(struct.pack("<IIII", acc.vert_count(), len(acc.idx) // 3, shell_v, shell_t))
        f.write(struct.pack("<%df" % len(acc.pos), *acc.pos))
        f.write(struct.pack("<%df" % len(nrm), *nrm))
        f.write(struct.pack("<%df" % len(ao), *ao))
        f.write(struct.pack("<%dI" % len(acc.idx), *acc.idx))
    report.append({
        "id": mod["id"],
        "verts": acc.vert_count(),
        "tris": len(acc.idx) // 3,
        "shellVerts": shell_v,
        "shellTris": shell_t,
        "aoMin": round(min(ao), 4),
        "aoMax": round(max(ao), 4),
    })

print("CAVE-BUILD " + json.dumps(report))
